package com.example.car.mapper;

import com.example.car.common.PageObject;
import com.example.car.common.PageResult;
import com.example.car.entity.BrokeInfoEntity;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BrokeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokeInfo
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokeInfo
     *
     * @mbg.generated
     */
    int insert(BrokeInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokeInfo
     *
     * @mbg.generated
     */
    int insertSelective(BrokeInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokeInfo
     *
     * @mbg.generated
     */
    BrokeInfoEntity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokeInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BrokeInfoEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table brokeInfo
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BrokeInfoEntity record);

    int getListCount(@Param("brokeInfoEntity") BrokeInfoEntity brokeInfoEntity);

    List<BrokeInfoEntity> getList(@Param("pageObject")PageObject pageObject, @Param("brokeInfoEntity") BrokeInfoEntity brokeInfoEntity);

    List<String> getBrokeImgList(Integer brokeInfoId);

    int insertImg( @Param("imgList")List<String> imgList,@Param("brokeInfoId") Integer brokeInfoId);

    void delImgs(Integer id);
}